### ISSUE TITLE
How to include trace id in response header?

### ISSUE THREAD

**Issue by npuichigo** [Blueswen/fastapi-observability#12]
I tried to add one middleware like
```
class CaptureTraceIdInResponse(BaseHTTPMiddleware):
    def __init__(self, app):
        super().__init__(app)

    async def dispatch(self, request: Request, call_next):
        trace_id = trace.get_current_span().get_span_context().trace_id
        response = await call_next(request)
        response.headers["X-Trace-Id"] = trace.format_trace_id(trace_id)

        return response
```
but failed. Could you help to give some guidance?

**Comment by npuichigo** [comment]
It seems that I need to add middleware before calling setting otlp. It works for me now, but I have no idea why should it be that.

**Comment by blueswen** [comment]
Not sure what error you got. Following middleware code is work for me:

```py
from fastapi import FastAPI, Request, Response
from opentelemetry import trace
from opentelemetry.propagate import inject
from starlette.middleware.base import BaseHTTPMiddleware

class CustomHeaderMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        response = await call_next(request)
        inject(response.headers) # leverage inject function
        span = trace.get_current_span()
        trace_id = trace.format_trace_id(span.get_span_context().trace_id)
        response.headers["My-Trace-Id"] = trace_id # only retrieve trace ID 
        return response
```

The response header looks like:

![resp-header-sampel](https://github.com/blueswen/fastapi-observability/assets/1564148/6a9e76cb-8122-4b72-8bc3-89b6a5a6f81a)

**Comment by npuichigo** [comment]
I add this middleware after setting otlp so it failed to show correct trace id

**Comment by blueswen** [comment]
Try my middleware from the previous reply, or provide logs of your application, responses from the application, and trace data screenshots on Grafana for more drill-down discussion.
