### ISSUE TITLE
docker loki plugin not found

### ISSUE THREAD

**Issue by cenkerozkan** [Blueswen/fastapi-observability#17]
In your document, if an error is encountered regarding the loki plugin not being found, you have directed us to enable the loki plugin. It is meaningless to do this without installing the loki plugin. I would like to add the necessary additional information to the document.

**Comment by cenkerozkan** [comment]
If loki docker plugin is not installed
```bash
docker plugin install grafana/loki-docker-driver:2.9.2 --alias loki --grant-all-permissions
```

**Comment by blueswen** [comment]
@cenkerozkan, thanks for the information! I will add this to the document.
