### ISSUE TITLE
proper steps

### ISSUE THREAD

**Issue by Nutan-Ust** [Blueswen/fastapi-observability#7]
please give appropriate steps to run the code and how to set grafana, how to send data to grafana

**Comment by blueswen** [comment]
The data source is added by config file in `etc/grafana/datasource.yml`. Check more details at https://github.com/blueswen/fastapi-observability#grafana and https://grafana.com/docs/grafana/latest/administration/provisioning/. And the data is not been sent to Grafana, they are queried by Grafana from different data backends like Prometheus, Tempo, and Loki.
