### ISSUE TITLE
Q: Is the presence of a /metrics endpoint in FastAPI necessary with Loki setup in K8s?

### ISSUE THREAD

**Issue by monometa** [Blueswen/fastapi-observability#8]
Hello, @blueswen 

Big thanks for sharing that demo setup. I am currently trying to set up the PLG stack in K8s and integrate it with FastAPI

I am just starting to delve into DevOps, but I am closely collaborating with a DevOps guy who believes that Loki is sufficient for gathering and storing logs from pods.

I will be glad if you can share your opinion about it and the need for PrometheusMiddleware in that case

**Comment by blueswen** [comment]
Hi @monometa 

Glad this project helped you.

However, I am unsure what you are asking. Could you give more details about what you are trying to do or not to do?

**Comment by monometa** [comment]
@blueswen Sorry for the confusion

I mean we already have the following helm charts specified below and the question is do I need to create an endpoint /metrics to allow Prometheus to collect the data or the same work can be done using Loki and Promtail only? Without the need to create an endpoint and corresponding middleware which is called PrometheusMiddleware and provided in the utils module?

https://artifacthub.io/packages/helm/grafana/loki-stack
https://artifacthub.io/packages/helm/bitnami/kube-prometheus

**Comment by blueswen** [comment]
@monometa 

PrometheusMiddleware is responsible for providing metrics of FastAPI applications like the request duration of each API.  If you want to get more details about your application by metrics, the PrometheusMiddleware is required.

Loki Stack helm chart only collects logs from containers, so it can't provide any metrics of your application.
Kube Prometheus helm chat only creates a Prometheus service and provides some node exporters and the ability to discover services or pods. It can't provide any metrics of your application as well.

You can check the architecture diagram on top of the readme. The arrow direction implies who created the data and who is responsible for collecting the data.

**Comment by monometa** [comment]
@blueswen Thanks for the detailed comment, it helped put some points in the right places
